### ISSUE TITLE
memory requirements

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [BUStools/Notebooks#4]
Currently unable use the following:
`> ScaleData(hgmm1k, overwrite = TRUE, chunk.size = NULL, chunk.dims = NULL)`
`Error: cannot allocate vector of size 21.2 Gb`

**Comment by lambdamoses** [comment]
You can set the arguments `chunk.size` and `chunk.dims`; the default setting in Seurat is `chunk.size = 1000` and `chunk.dims = c(256,256)`. Using `NULL` will make `loomR` automatically determine those values, resulting into larger chunks, or more data loaded into memory at a time. Part of the problem is that `loomR` is using dense matrix rather than sparse matrix here.
